# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ASP.NET Core API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup ASP.NET Core API
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore OrderManagementSystem.slnx

    - name: Build
      run: dotnet build OrderManagementSystem.slnx --no-restore

    - name: Test
      run: dotnet test OrderManagementSystem.slnx --no-build --verbosity normal
